[tool.check-manifest]
ignore = ["*.swp"]

[tool.ruff]
extend-exclude = [
    ".venv",
    "migrations",
]
ignore = [
    "E402",
    "E501",
]
select = [
    "E",
    "F",
    "W",
]

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = "src/"
known_first_party = "nameko_chassis"

[tool.mypy]
python_version = "3.10"
mypy_path = "src/"
namespace_packages = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = [
    "eventlet.*",
    "nameko.*",
    "nameko_opentelemetry.*",
    "nameko_prometheus.*",
    "nameko_sentry.*",
    "pyrabbit.*",
    "pytest.*",
    "raven.*",
]

ignore_missing_imports = true

[tool.pytest.ini_options]
norecursedirs = [".git", ".tox", "dist", "build"]
testpaths = ["tests"]
