name: nameko-chassis CI build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: astral-sh/setup-uv@v6
      - name: Upgrade pip
        run: pip install pip setuptools wheel --upgrade
      - name: Install tox
        run: pip install tox tox-gh-actions tox-uv
      - name: Run tox
        run: python -m tox
